apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secrets-provider
  namespace: staging
spec:
  provider: azure
  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: appInsightsConnectionString
          key: appInsightsConnectionString
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "470816f9-9fc8-41c0-9902-2b167a22f2f5"
    keyvaultName: "kvecombalvin07301"
    tenantId: "b1d38173-7030-4cb2-93cb-796171a55cae"
    objects: |
      array:
        - |
          objectName: appInsightsConnectionString
          objectType: secret
