apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secrets-provider
  namespace: production
spec:
  provider: azure
  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: appInsightsConnectionString
          key: appInsightsConnectionString
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "__KEYVAULT_NAME__"
    tenantId: "__TENANT_ID__"
    objects: |
      array:
        - |
          objectName: appInsightsConnectionString
          objectType: secret
